apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-web
  namespace: nginx
  labels:
    app: nginx-web
spec:
  replicas: 2
  podManagementPolicy: Parallel
  serviceName: nginx-web
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      volumes:
      - name: nginx-web
        persistentVolumeClaim:
          claimName: nginx-web
      - name: nginx-v 
        configMap:
          name: nginx-v
          items:
            - key: version.txt
              path: version.txt
      # securityContext:
      #   fsGroup: 101
      #   runAsGroup: 101
      #   runAsNonRoot: true
      #   runAsUser: 101      
      imagePullSecrets:
      - name: regcredjf  
      containers:
      - name: nginx-web
        image: simone1984.jfrog.io/docker/nginx-web:1.19.1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NGINX_WEB
            value: "http://127.0.0.1:80"
        volumeMounts:
        - name: nginx-web
          mountPath: /var/log/nginx
        - name: nginx-v
          mountPath: /tmp/version.txt
          subPath: version.txt
        ports:
          - containerPort: 80
            name: nginx-web
        readinessProbe:
          httpGet:
            # path: /index.html
            port: 80
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            # path: /index.html
            port: 80
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v
  namespace: nginx
data:
  version.txt: |
    Release_Number
    V: 1.19.2