apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-web
  namespace: nginx
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginx-web"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-web
  namespace: nginx
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi