name: Nginx-deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag the image"
        default: 1.19.1
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # - name: Docker build and Push
      #   env:
      #     token: ${{ secrets.jfrogtoken }}
      #     user: ${{ secrets.jfroguser }}
      #     registry: ${{ secrets.registry }}
      #     repo: "docker"

      #   run: |
      #     docker build . -t nginx:${{ inputs.tag }}
      #     echo ${token} |docker login -u${user} ${registry} --password-stdin
      #     docker tag nginx:${{ inputs.tag }} $registry/$repo/nginx:${{ inputs.tag }}
      #     docker push ${registry}/${repo}/nginx:${{ inputs.tag }}

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: actions-hub/kubectl@master
        with:
          args: get pods -n nginx


      